annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-rules/issues\n"
chartApiVersion: v2
chartFile: prometheus-rules-4.114.2-dev.renovate-c--e-pint-0-x.2026-08-21.15-53-08.h3781ab3.tgz
dateCreated: '2026-08-21T15:53:31.405784Z'
digest: 0b6ce8de3dacdfeb17b2a882744e173882cba135179dcfc42e19ca258102f583
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
