annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-rules/issues\n"
chartApiVersion: v2
chartFile: prometheus-rules-4.119.1-dev.teams-alignment-branch.2026-09-06.10-32-40.h05cb7e8.tgz
dateCreated: '2026-09-06T10:33:05.301063Z'
digest: 3c9ddc7254f4fa47fc5b50bbe7b26f91df9312d7c44d2e31b1cb8d1061d9929f
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
