annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.67.0-d2fb485ad08eafc4c6df39ccfe52ef465f7cb899.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.67.0-d2fb485ad08eafc4c6df39ccfe52ef465f7cb899.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.67.0-d2fb485ad08eafc4c6df39ccfe52ef465f7cb899.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.67.0-d2fb485ad08eafc4c6df39ccfe52ef465f7cb899.tgz
dateCreated: '2025-06-30T09:53:52.169252Z'
digest: db5e0d9dd3a8f6eccbb80e84f5a4b22a94786a8d967f9389a5e4139d1e3147fc
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
