annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-rules/issues\n"
chartApiVersion: v2
chartFile: prometheus-rules-4.117.1-dev.phoenix-op--es-removal.2026-08-25.11-23-51.h3b66226.tgz
dateCreated: '2026-08-25T11:24:40.840196Z'
digest: 698f521a3ab9dae7bb0540074f8d8b34a552034f8ff08f78dec88e69b787b580
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
