annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-rules/issues\n"
chartApiVersion: v2
chartFile: prometheus-rules-4.117.1-dev.add-loggin--node-alert.2026-08-31.13-18-58.hded7e41.tgz
dateCreated: '2026-08-31T13:19:57.761839Z'
digest: 1b80479924ffa310d7a4678ba90d36e377965ec3c2555b6144d058e46b012bd7
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
