annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.43.0-7a1eb20a7dfa35285349fb32487654ae2cb1feba.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.43.0-7a1eb20a7dfa35285349fb32487654ae2cb1feba.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.43.0-7a1eb20a7dfa35285349fb32487654ae2cb1feba.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v1
chartFile: prometheus-rules-4.43.0-7a1eb20a7dfa35285349fb32487654ae2cb1feba.tgz
dateCreated: '2025-02-20T13:51:32.124902Z'
digest: 6179a73986e942c55dabd96a89e22e092cb2820a3c76098364d13854b7a153d8
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
