annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.3.0-2e7a065ce2e69ea6d106e166c6a3d028e2751e5f.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.3.0-2e7a065ce2e69ea6d106e166c6a3d028e2751e5f.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.3.0-2e7a065ce2e69ea6d106e166c6a3d028e2751e5f.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.3.0-2e7a065ce2e69ea6d106e166c6a3d028e2751e5f.tgz
dateCreated: '2025-10-01T22:38:48.284810Z'
digest: e5525fe51e1fa6da99d425a97de722f4d2f2133bfcec504f05414f2ad9d9130d
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
