annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-rules/issues\n"
chartApiVersion: v2
chartFile: prometheus-rules-4.119.2-dev.renovate-a--itect-10-x.2026-09-11.15-15-17.h0f626cc.tgz
dateCreated: '2026-09-11T15:15:38.420201Z'
digest: 7f9409a91bcd5bd0b964823b97a48f5cd3c9e6bd40d059cca4a4de975963cb3a
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
