annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.62.0-53bf7e2cb32aef9c2e8a84ef04fa2b41d28c027a.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.62.0-53bf7e2cb32aef9c2e8a84ef04fa2b41d28c027a.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.62.0-53bf7e2cb32aef9c2e8a84ef04fa2b41d28c027a.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.62.0-53bf7e2cb32aef9c2e8a84ef04fa2b41d28c027a.tgz
dateCreated: '2025-05-20T12:53:50.628387Z'
digest: 26deab8c7cbb962d2c20adb132a911ba72b1547051bff956b12ba72487354e1f
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
