annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.65.1-e9a32ca375d0664de06410ff26285640037cfc4b.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.65.1-e9a32ca375d0664de06410ff26285640037cfc4b.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.65.1-e9a32ca375d0664de06410ff26285640037cfc4b.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.65.1-e9a32ca375d0664de06410ff26285640037cfc4b.tgz
dateCreated: '2025-06-23T12:33:40.992697Z'
digest: b66a9bf97167cfbed9caa0b16a96f87068895d13d7ecda7e6b1ded7a3f2dbc19
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
