annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.2.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.2.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.2.0.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.2.0.tgz
dateCreated: '2025-08-20T08:06:43.199172Z'
digest: 8aebc4830fbd202e5da0736f167f159564964f91cb49c4f589c5bb0df9edfdc2
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
