annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.73.2-ed2f8957754dcf412b16b62b5cbc1bb926cc00ac.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.73.2-ed2f8957754dcf412b16b62b5cbc1bb926cc00ac.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.73.2-ed2f8957754dcf412b16b62b5cbc1bb926cc00ac.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.73.2-ed2f8957754dcf412b16b62b5cbc1bb926cc00ac.tgz
dateCreated: '2025-09-02T14:50:20.566157Z'
digest: 985e2773d0d134bf051f4c9467205e397e0fc4f01cf742e7eaad75f487cca618
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
