annotations:
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.89.0-70fb5d9ee82dc6051cadb6b7afd7589dc07cff65.tgz
dateCreated: '2025-12-17T17:15:48.033348Z'
digest: 33148ba719836ea4d625f63a801db571d9beb80378e0d8e8f1eb7b933d628194
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
