annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-rules-4.96.1-ce6537ee5915569a9d6e729a486c1d94207d6704.tgz
dateCreated: '2026-02-26T17:46:25.666893Z'
digest: dd7c8d1b9e04579d5a0fe122be9ccf317e83e5bd3003b49ac06a7c44901c0bed
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
