annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.4.0-59b8a833870b37727b4ffcde2b1f13245b8e0519.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.4.0-59b8a833870b37727b4ffcde2b1f13245b8e0519.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.4.0-59b8a833870b37727b4ffcde2b1f13245b8e0519.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.4.0-59b8a833870b37727b4ffcde2b1f13245b8e0519.tgz
dateCreated: '2025-12-04T15:45:58.403966Z'
digest: 213253645ce9f41688a2b3d560fbf9fc44af626379ab5db9d1bd31315e6fb663
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
