annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.86.0-dbfd456ee5b67b6c3eb289b03adc3aae7791e3fb.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.86.0-dbfd456ee5b67b6c3eb289b03adc3aae7791e3fb.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.86.0-dbfd456ee5b67b6c3eb289b03adc3aae7791e3fb.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.86.0-dbfd456ee5b67b6c3eb289b03adc3aae7791e3fb.tgz
dateCreated: '2025-11-30T22:35:16.732692Z'
digest: 076df6b37e587cbf4c459a7565dbeecb2c9243abb37eb4ae36b3b656bd2dccf0
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
