annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.72.4-e1679d5d7753400f737b917955d593c6985e4699.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.72.4-e1679d5d7753400f737b917955d593c6985e4699.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.72.4-e1679d5d7753400f737b917955d593c6985e4699.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.72.4-e1679d5d7753400f737b917955d593c6985e4699.tgz
dateCreated: '2025-07-31T09:19:31.557013Z'
digest: 333c933a75178ec2591630df4b48685d9cd3f3f25de3b3cf5abb74d5f600490e
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
