annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.4.0-3368e7b01bc63e428ebe5c000791cf94fd619503.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.4.0-3368e7b01bc63e428ebe5c000791cf94fd619503.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-remotewrite-1.4.0-3368e7b01bc63e428ebe5c000791cf94fd619503.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.4.0-3368e7b01bc63e428ebe5c000791cf94fd619503.tgz
dateCreated: '2025-10-31T13:01:40.146706Z'
digest: e0bb96df83572993fb1bef6612f8e0184d00ccba538ef159094b4a9c33497315
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
