annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-rules/issues\n"
chartApiVersion: v2
chartFile: prometheus-rules-4.117.1-dev.renovate-c--e-pint-0-x.2026-08-31.09-48-09.he0e5627.tgz
dateCreated: '2026-08-31T09:48:32.310405Z'
digest: 02eb04948c0cacd941941d47ca641dc8ecded98001c0965a3d7e3dea7d865b91
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
