annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.65.1-62e3df8e83e3e04c6dc3f1073505f050265303c8.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.65.1-62e3df8e83e3e04c6dc3f1073505f050265303c8.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.65.1-62e3df8e83e3e04c6dc3f1073505f050265303c8.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.65.1-62e3df8e83e3e04c6dc3f1073505f050265303c8.tgz
dateCreated: '2025-06-16T14:16:53.374796Z'
digest: c9c881fbe2596704dcc3b382f8a509d5a8735e6414595daa953a84b01df61c67
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
