annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.83.0-3d42e3f28129c58d2b33a7ea0aeb0480c99c0186.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.83.0-3d42e3f28129c58d2b33a7ea0aeb0480c99c0186.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.83.0-3d42e3f28129c58d2b33a7ea0aeb0480c99c0186.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.83.0-3d42e3f28129c58d2b33a7ea0aeb0480c99c0186.tgz
dateCreated: '2025-11-10T09:12:04.722623Z'
digest: 563db1934426a9df29ea4f319db548520f73bb9b486bd5f99fb6bbe9ce7498ed
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
