annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.44.0-e52ccbc6dd47955efd9aeaa5e02f61f9db1049e4.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.44.0-e52ccbc6dd47955efd9aeaa5e02f61f9db1049e4.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.44.0-e52ccbc6dd47955efd9aeaa5e02f61f9db1049e4.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v1
chartFile: prometheus-rules-4.44.0-e52ccbc6dd47955efd9aeaa5e02f61f9db1049e4.tgz
dateCreated: '2025-02-24T12:48:43.646980Z'
digest: a3ab7c9697d56c9e5f63b2b75bf132b38f2832fde9d779d4a4f1347c23532fe2
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
