annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.63.0-de705aaf60b1276e45b4d0404ff9ac1eabafa77f.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.63.0-de705aaf60b1276e45b4d0404ff9ac1eabafa77f.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.63.0-de705aaf60b1276e45b4d0404ff9ac1eabafa77f.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.63.0-de705aaf60b1276e45b4d0404ff9ac1eabafa77f.tgz
dateCreated: '2025-06-05T12:22:44.712178Z'
digest: a8d9c927d91802ffe0ee2d1b65b52f4e04ab5fc728edd77efd42e27cf5756096
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
