annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.72.3-3ae2925629ed89364f2f337ee34757c9fe951bf5.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.72.3-3ae2925629ed89364f2f337ee34757c9fe951bf5.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.72.3-3ae2925629ed89364f2f337ee34757c9fe951bf5.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.72.3-3ae2925629ed89364f2f337ee34757c9fe951bf5.tgz
dateCreated: '2025-07-31T08:36:21.916236Z'
digest: 2331396c244265251d372added7d565bbb7dfdcbf815eb13283d41793a937f30
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
