annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-rules/issues\n"
chartApiVersion: v2
chartFile: prometheus-rules-4.117.1-dev.honeybadge--rvice-cidr.2026-08-25.08-50-03.h4cb8bf5.tgz
dateCreated: '2026-08-25T08:50:25.122494Z'
digest: 9fbdabc578b7297e2b18f548c2064c731da6d39207f9f37973b0fd27fa92c48a
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
