annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.85.0-e5da148e67d431fb94c50090cfac6a5c8aa11412.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.85.0-e5da148e67d431fb94c50090cfac6a5c8aa11412.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.85.0-e5da148e67d431fb94c50090cfac6a5c8aa11412.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.85.0-e5da148e67d431fb94c50090cfac6a5c8aa11412.tgz
dateCreated: '2025-11-24T10:21:36.553933Z'
digest: 9dba0b6501f8165692f62c73fbd8477ca7d04996c875e8d57f4803f691252f23
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
