annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-rules-4.111.1-dev.teams-alignment-branch.2026-07-11.12-23-42.h1eb36a1.tgz
dateCreated: '2026-07-11T12:24:05.645785Z'
digest: b2488155e3b2b6527337de3df725138727fded5c520741a3e00bbae1d7b53042
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
