annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.81.0-009105411e47b779889d6d43980582be54951dd7.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.81.0-009105411e47b779889d6d43980582be54951dd7.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-test-catalog/prometheus-rules-4.81.0-009105411e47b779889d6d43980582be54951dd7.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-rules-4.81.0-009105411e47b779889d6d43980582be54951dd7.tgz
dateCreated: '2025-11-04T10:38:04.825119Z'
digest: 7076bb16f7384c34b2c2b5118881b1036ace15f32e02476415789f8cb612c2de
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
