annotations:
  application.giantswarm.io/team: atlas
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: !!python/object/new:app_build_suite.build_steps.helm_consts.BlockLiteralStr
  - "- name: Support\n  url: https://github.com/giantswarm/prometheus-remotewrite/issues\n"
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.5.1-rbf28cd64t20260925081254h93a071b.tgz
dateCreated: '2026-09-25T08:13:26.653366Z'
digest: de8eb8457923c3a1348c1f80cf954c557345ced088179999b67f921bea71a806
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
