annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.4.1-25d0f0aa6417bbb522886065ffb2dd2757c2521a.tgz
dateCreated: '2026-02-12T15:33:34.253508Z'
digest: 70e9841baf53a2900801ca28f5fdbb53f4c9da36a7d6f5f89250489ec872c4fd
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
