annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.5.1-dev.renovate-architect-9-x.2026-06-22.09-49-13.h2b2d57f.tgz
dateCreated: '2026-06-22T09:49:44.872582Z'
digest: e9f9c70551a100f1a9cb26594acadf731f2d6fc6d8b9b030d1928218accf87d6
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
