annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-rules-4.100.0-c616e376e0d8dc120d93869048eaac5c532e7cb6.tgz
dateCreated: '2026-03-27T14:10:05.622324Z'
digest: 4fb04e951dd362a00b7c5109643352a77c7b8bac04ca922aee916da49cb381fa
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
