annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-remotewrite-1.4.4-bc7b303955eae448557e8548252200e12b5ce025.tgz
dateCreated: '2026-03-03T11:12:17.329597Z'
digest: 177b7cf8b60e0e83e8762dabdb2b5ef541ca409ef618eb13e0e8e110bb84b319
home: https://github.com/giantswarm/prometheus-remotewrite
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
