annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-rules-4.107.1-dev.renovate-c--e-pint-0-x.2026-06-11.16-35-21.h058fcb7.tgz
dateCreated: '2026-06-11T16:35:53.626770Z'
digest: d754f852ae491fbd2203521e67d93f67211d76627910d8c91e4d7f25dc6aad66
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
